import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={` min-h-screen  ${inter.className}`}>
        <main className="lg:p-24 md:p-24 sm:p-20 p-5">
          <div>{children}</div>
        </main>
      </body>
    </html>
  );
}
